config/routes.rb
Whichizrite::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"},
                      :controllers => {:registrations => "users/registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
    get "login",    :to => "users/sessions#new"
    get "logout",   :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete",   :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to => "users/registrations#password"
    patch "settings/password" => "users/registrations#settings_password"
    put "settings/password" => "users/registrations#settings_password"
    get "settings/privacy", :to => "users/registrations#privacy"
    patch "settings/privacy" => "users/registrations#settings_privacy"
    put "settings/privacy" => "users/registrations#settings_privacy"
  end 

  get 'feed', to: 'pages#feed'

  resources :users do
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :visibility
      get :unpend
    end
  end

  
  resources :pages

  resources :posts do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments do
    member do
      get :vote_up
      get :vote_down
      get :unvote
    end
  end
  resources :votes

  get 'categories/:category', to: 'posts#index', as: :category

  get 'tags/:tag', to: 'posts#index', as: :tag

  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  include PgSearch
  include RailsSettings::Extend
  extend FriendlyId
  friendly_id :username, use: [:slugged]
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, 
         :omniauthable

  # before_create :set_username
  # after_create  :store_settings

  multisearchable :against => [:name, :username, :email]

  # attr_accessible :username, :email, :name, :password, :password_confirmation, :remember_me, :login,
  #                 :aboutme, :dob, :avatar, :location, :country_name, :sex, :uid, :provider, :profilepic, 
  #                 :auth_token, :aboutme_html

  attr_accessor :login

  has_many    :posts, dependent: :destroy
  has_many    :comments

  acts_as_voter

  acts_as_follower_plus
  acts_as_followable_plus

  has_attached_file :avatar, styles: {thumb: "30x30#", small: "100x100#", 
                                    med:"350x350#", large:"500x500>"},
                  default_url: "/assets/default/:style/no-image.png",
                  url:  "/assets/images/users/:id/album/:style/:basename.:extension",
                  path: ":rails_root/public/assets/images/users/:id/album/:style/:basename.:extension"

  validates_attachment :avatar, content_type: {content_type: ["image/jpeg", "image/png", 
                                                        "image/bmp", "image/jpg", "image/gif"]},
                                size: {less_than: 5.megabytes}

  before_save{|user| user.email = email.downcase}

  VALID_EMAIL_REGEX = /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  VALID_USERNAME_REGEX = /[a-zA-Z0-9_\.]/
  VALID_NAME_REGEX = /[\w\s\-]/
  validates :name, presence: true
  validates :email, presence: true, uniqueness: {case_sensitive:false}
  validates :email, format: {with: VALID_EMAIL_REGEX}                             
  validates :password, presence: true, length: {minimum: 8, maximum: 25}, on: :create
  validates :password, length: {minimum: 8, maximum: 25}, on: :update, allow_blank: true

  has_settings_on :hide_profile, :fb_pub_comment, :fb_pub_post, :fb_pub_vote,
                  :email_post_comment, :email_comment_vote, :email_follow_alert,
                  :email_profile_update, :email_post_vote

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(name:auth.info.name,
                           provider:auth.provider,
                           uid:auth.uid,
                           username: auth.info.nickname,
                           email:auth.info.email,
                           sex: auth.extra.raw_info.gender,
                           password:Devise.friendly_token[0,20],
                           auth_token: auth.credentials.token
                           )
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def feed
    Post.from_users_followed_by(self)
  end

  def myfeed
    Post.posts_from_me(self)
  end  
  
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def facebook
    @fb_user ||= FbGraph::User.me(self.auth_token)
  end

  def fbconnect(story, title, url)    
    app = FbGraph::Application.new(FACEBOOK_CONFIG['app_id'])
    me = FbGraph::User.me(self.auth_token)

    ## Custom Action (you need to configure them in your app setting)

    # Fetch activities
    actions = me.og_actions app.og_action(story)

    # Publish an activity
    action = me.og_action!(
      app.og_action(story),
      :article => 'http://samples.ogp.me/434264856596891'
    )
  end

  def fbsignup    
    app = FbGraph::Application.new(FACEBOOK_CONFIG['app_id'])
    me = FbGraph::User.me(self.auth_token)

    ## Custom Action (you need to configure them in your app setting)

    # Fetch activities
    actions = me.og_actions app.og_action(:connect)

    # Publish an activity
    action = me.og_action!(
      app.og_action(:connect),
      :object => 'http://samples.ogp.me/434264856596891'
    )
  end

  def fb_publish(post_title, post_url)

    #Check if user is connected to facebook
    if self.provider == 'facebook'
      
      #Check if the user as any special settings
      if self.settings.all != nil
        
        #Define facebook action type
        if self.settings.fb_pub_post = '1'
          story = 'create'
        elsif self.settings.fb_pub_vote = '1'
          story = 'vote'
        else
          story = 'comment'
        end
        
      end

      #Publish comment
      self.fbconnect(story, post_title, post_url)
    end    
  end

  private 
    def set_username
      username = self.email[/^[^@]+/]
      if User.find_by_username(username) != nil
        self.username = "#{username}.#{User.last.id.to_s[0..3]}"
      else        
        self.username = "#{self.email[/^[^@]+/]}"
      end
    end

    def store_settings
      if self.provider == 'facebook'
        self.settings.hide_profile = '1' 
        self.settings.fb_pub_post = '1' 
        self.settings.fb_pub_vote = '1' 
        self.settings.fb_pub_comment = '1' 
        self.save
      else
        self.email_post_comment = '1' 
        self.email_comment_vote = '1' 
        self.email_follow_alert = '1'
        self.email_profile_update = '1' 
        self.email_post_vote = '1'
        self.save
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      # @after_sign_in_url = after_sign_in_path_for(@user)
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      # render 'callback', :layout => false

      # # if params[:state] == 'popup'
      # #   render 'callback', :layout => false
      # # else
      # #   redirect_to @after_sign_in_url
      # # end
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
	prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy, :password]

    def settings_password
    	@disable_chan = true
    	@user = current_user
    	Rails.logger.info "entered if settings_password"
    	if @user.update_with_password(devise_parameter_sanitizer.sanitize(:edit_password))    		
    		#Sign in the user by passing validation in case his password has changed
    		sign_in @user, :bypass => true
    		flash[:success] = "Password updated"
    		Rails.logger.info(devise_parameter_sanitizer.sanitize(:edit_password).inspect)
    		redirect_to settings_password_path
    	else
    		Rails.logger.info(@user.errors.inspect)
    		# flash[:warning] = "Password not updated"
    		render 'password'
    	end
    end

    def settings_privacy
    	@disable_chan = true
    	@user = current_user
    	Rails.logger.info "entered if settings_privacy"
    	if @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))    		
    		#Sign in the user by passing validation in case his password has changed
    		sign_in @user, :bypass => true
    		flash[:success] = "Settings updated"
    		Rails.logger.info(devise_parameter_sanitizer.sanitize(:account_update).inspect)
    		redirect_to settings_privacy_path
    		UserMailer.profile_update(resource).deliver
    	else
    		Rails.logger.info(@user.errors.inspect)
    		# flash[:warning] = "Password not updated"
    		render 'password'
    	end
    end

    def create
    	@disable_chan = true
	    build_resource(sign_up_params)

	    if resource.save
	      if resource.active_for_authentication?
	        # set_flash_message :notice, :signed_up if is_navigational_format?
	        flash[:success] = "Welcome to the community. Please remember to update your profile information."
	        sign_up(resource_name, resource)
	        respond_with resource, :location => after_sign_up_path_for(resource)
	        if resource.provider == "facebook"	        	
	        	resource.fbsignup
	        end
	        UserMailer.welcome(resource).deliver
	      else
	        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
	        expire_session_data_after_sign_in!
	        respond_with resource, :location => after_inactive_sign_up_path_for(resource)
	      end
	    else
	      clean_up_passwords resource
	      respond_with resource
	    end
	end
	def update
		@disable_chan = true
		@user = User.find(current_user.id)

		successfully_updated = if needs_password?(@user, params)
		  @user.update_with_password(devise_parameter_sanitizer.sanitize(:account_update))
		else
		  # remove the virtual current_password attribute update_without_password
		  # doesn't know how to ignore it
		  params[:user].delete(:current_password)
		  @user.update_without_password(devise_parameter_sanitizer.sanitize(:account_update))
		end

		if successfully_updated
		  # set_flash_message :notice, :updated
		  # Sign in the user bypassing validation in case his password changed
		  sign_in @user, :bypass => true
		  redirect_to after_update_path_for(@user)
		  flash[:success] = "Profile updated"
	      UserMailer.profile_update(@user).deliver
		else
		  render "edit"
		end
	end
	# def update
	# 	self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)

	# 	# If the user has filled in any of the password fields, we'll update their password
	# 	any_passwords = %w(password password_confirmation current_password).any? do |field|
	# 	  params[resource_name][field].present?
	# 	end
	# 	update_method = any_passwords ? :update_with_password : :update_without_password

	# 	if resource.send(update_method, account_update_params)
	# 	  set_flash_message :notice, :updated if is_navigational_format?
	# 	  sign_in resource_name, resource, :bypass => true
	# 	  respond_with resource, :location => after_update_path_for(resource)
	# 	  flash[:success] = "Profile updated"
	# 	  UserMailer.profile_update(resource).deliver
	# 	else
	# 	  clean_up_passwords(resource)
	# 	  respond_with_navigational(resource){ render :edit }
	# 	end
	# end

	private
	# check if we need password to update user data
	# ie if password or email was changed
	# extend this as needed
		def needs_password?(user, params)
			user.email != params[:user][:email] ||
			params[:user][:password].present?
		end	
  
	protected
		def after_update_path_for(resource)
			settings_path(resource)
			# user_path(resource)
		end

		def after_sign_up_path_for(resource)
			user_path(resource)
			# user_path(resource)
		end

end

app/controllers/users/sessions_controller.rb
class SessionsController < Devise::
	def new
		@disable_chan = true
	end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
	before_filter :authenticate_user!, only: [:index, :edit, :update, :destroy, :make_private, :make_public]
	before_filter :correct_user, only: [:edit, :update]
	before_filter :admin_user, only: :destroy

	def show
		@user = User.friendly.find(params[:id])
		@disable_chan = true
		if current_user == @user
			@feed_items = @user.myfeed.paginate(page: params[:page])
		else
			@feed_items = @user.posts.paginate(page: params[:page])
		end
	end

	def index
		@disable_chan = true
		@users = User.paginate(page: params[:page])
	end

	# def search
	# 	@users = User.user_search(params[:query]).paginate(page: params[:page])
	# end

	def destroy
		User.friendly.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to :back
	end

	def following
	    @title = "Following"
	    @user = User.friendly.find(params[:id])
	    @users = @user.following_users.paginate(page: params[:page], per_page: 10)
	    render 'show_follow'
	end

	def followers
		@disable_chan = true
	    @title = "Followers"
	    @user = User.friendly.find(params[:id])
	    @users = @user.followers.paginate(page: params[:page], per_page: 10)
	    render 'show_followers'
	end

	def follow
		@disable_chan = true
		@user = User.friendly.find(params[:id])
		if current_or_guest_user.name == "Guest"
            flash[:notice] = "You need to be signed in to follow a user"
            redirect_to login_path
        else
            current_user.follow(@user)			
			redirect_to :back
			flash[:notice] = "You are now following #{@user.username}."
			# current_user.notify_follow(@user)
			# RecommenderMailer.new_follower(@user).deliver if @user.notify_new_follower
			UserMailer.follow_alert(@user, current_user).deliver
        end		
	end

	def unfollow
		@disable_chan = true
		@user = User.friendly.find(params[:id])		
		if current_or_guest_user.name == "Guest"
            flash[:notice] = "You need to be signed in to unfollow a user"
            redirect_to login_path
        else
            current_user.stop_following(@user)
			redirect_to :back
			flash[:notice] = "You are no longer following #{@user.username}."
			# current_user.notify_unfollow(@user)
        end	
	end

	def unpend
		@disable_chan = true
		@user = User.friendly.find(params[:id])
		current_user.unpend(@user)
		redirect_to :back
		flash[:success] = "You are no longer following #{@user.username}."
		# current_user.notify_pending(@user)
	end


	def visibility
		@disable_chan = true
		# @user = User.friendly.find(params[:id])
		current_user.modify_pref('hide_profile')
		if current_user.is_set_to?('hide_profile')
			redirect_to :back
			flash[:notice] = "Your profile is now private"
		else
			redirect_to :back
			flash[:notice] = "Your profile is now public"
		end		
	end

	private

		def correct_user
			@user = User.friendly.find(params[:id])
			redirect_to(root_path) unless current_user?(@user)
		end

		def admin_user
			redirect_to(root_path) unless current_user.admin?
		end


end

app/views/users/_follow.html.erb
<%= form_for(current_user.follow(@user)) do |f| %>
	<div><%= f.hidden_field :followed_id %></div>
	<%= f.submit "Follow", class: "follow btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if signed_in? %>
	<% unless current_user?(@user) %>
		<div id="follow_form">
			<% if current_user.following?(@user) %>
				<%= link_to "Unfollow", unfollow_user_path(@user), :class => "unfollow btn btn-large" %>
			<% else %>
				<%= link_to "Follow", follow_user_path(@user), :class => "follow btn btn-large btn-primary" %>
			<% end %>
		</div>
	<% end %>
<% else %>
	<%= link_to "Follow", follow_user_path(@user), :class => "follow btn btn-large btn-primary" %>
<% end %>

app/views/users/_profile.html.erb
<div class="profile-info row">
	<div class="profile-pic col-xs-3 col-sm-3">
		<%= link_to avatar_for(@user, 'med'), @user %>		
	</div>
	<div class="profile-dets col-xs-9 col-sm-9">
		<div class="about-user">
			<div class="name">
				<span class="pull-left"><%= @user.name %></span>
				<%= render "follow_form" %>
			</div>
			<div class="misc">
				<i class="icon-home" style="padding-right: 3px"></i><%= @user.location %><span class="bullet"><i class="icon-circle"></i></span><% if @user.sex == "Male" %><i class="icon-male" style="padding-right: 3px"></i>Male<% elsif @user.sex == "Female" %><i class="icon-female" style="padding-right: 3px"></i>Female<% end %>
			</div>			
		</div>
		<div class="subscribers row">
			<div class="followers col-xs-6 col-sm-6">
				<span class="fol-lbl row"><a href="<%= followers_user_path(@user) %>">Followers (<%= @user.followers_count %>)</a></span>
				<% if @user.followers.any? %>
					<div class="user_avatars">
						<% @user.followers.first(7).each do |user_id| %>
							<% user = User.find(user_id) %>
							<%= link_to (image_tag user.avatar.url(:thumb)), user_path(user) %>
						<% end %>
					</div>
				<% end %>
			</div>
			<div class="following col-xs-6 col-sm-6">
				<span class="fol-lbl row"><a href="<%= following_user_path(@user) %>">Following (<%= @user.following_users_count %>)</a></span>
				<% if @user.following_users.any? %>
					<div class="user_avatars">
						<% @user.following_users.first(7).each do |user_id| %>
							<% user = User.find(user_id) %>
							<%= link_to (image_tag user.avatar.url(:thumb)), user_path(user) %>
						<% end %>
					</div>
				<% end %>
			</div>			
		</div>
	</div>
</div>

app/views/users/_profile_feed.html.erb
<% unless @feed_items.empty? %>
	<ol class="posts-list">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.unfollow,
		html: {method: :delete},
		remote:true) do |f| %>
	<%= f.submit "Unfollow", class: "unfollow btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
	<%= gravatar_for user, size: 52 %>
	<%= link_to user.name, user %>
	<% if current_user.admin? && !current_user?(user) %>
		| <%= link_to "delete", user, method: :delete,
						data: {confirm: "You sure?"} %>
	<% end %>
</li>

app/views/users/follow.js.erb
$('#follow_form').html('<%= escape_javascript(render :partial => "follow_form", :locals => {:user => @user}) %>');
// $("#followers").html('<%= @user.followers.count %>');
// $(".stories").html('<%= escape_javascript(render :partial => "story", :locals => (:user.story => @story)) %>');

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>

	<%= render 'shared/error_messages', object: f.object %>
	
		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation %>

	    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="main row">
	<div class="col-xs-12 col-sm-8">
		<%= render "profile" %>
		<div class="posts">
			<%= render "profile_feed" %>
		</div>
	</div>

	<!-- Side Bar -->
	<div class="hidden-xs col-sm-4">
		<%= render "shared/sidebar" %>
	</div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @user.name) %>
<div class="main row">
	<div class="span8">
		<%= render "profile" %>
		<div class="profile-chan">
			<h3>Following</h3>
			<% if @users.any? %>
				<ul class="users" >					
					<% @users.each do |user| %>
						<li id="<%= user.id %>">
							<div class="user row">
								<div class="pic span1">
									<%= link_to image_tag(user.avatar.url("med")), user_path(user) %>
								</div>
								<div class="info span6">
									<%= link_to user.name, user_path(user) %><br>
									<%= user.sex %> | <%= user.location %>
								</div>

								<div class="follow span1">
									<% if current_user.following?(user) %>
										<%= link_to "Unfollow", unfollow_user_path(user), :class => "btn btn-large" %>
									<% else %>
										<%= link_to "Follow", follow_user_path(user), :class => "btn btn-large btn-primary" %>
									<% end %>
								</div>
							</div>							
						</li>
					<% end %>
				</ul>
				<%= will_paginate @users %>
			<% end %>
		</div>
	</div>

	<!-- Side Bar -->
	<div class="span4">
		<%= render "shared/sidebar" %>
	</div>
</div>

app/views/users/show_followers.html.erb
<% provide(:title, @user.name) %>
<div class="main row">
	<div class="span8">
		<%= render "profile" %>
		<div class="profile-chan">
			<h3>Followers</h3>
			<% if @users.any? %>
				<ul class="users" >					
					<% @users.each do |user| %>
						<li id="<%= user.id %>">
							<div class="user row">
								<div class="pic span1">
									<%= link_to image_tag(user.avatar.url("med")), user_path(user) %>
								</div>
								<div class="info span6">
									<%= link_to user.name, user_path(user) %><br>
									<%= user.sex %> | <%= user.location %>
								</div>

								<div class="follow span1">
									<% if current_user.following?(user) %>
										<%= link_to "Unfollow", unfollow_user_path(user), :class => "btn btn-large" %>
									<% else %>
										<%= link_to "Follow", follow_user_path(user), :class => "btn btn-large btn-primary" %>
									<% end %>
								</div>
							</div>							
						</li>
					<% end %>
				</ul>
				<%= will_paginate @users %>
			<% end %>
		</div>
	</div>

	<!-- Side Bar -->
	<div class="span4">
		<%= render "shared/sidebar" %>
	</div>
</div>

app/views/users/unfollow.js.erb
$('#follow_form').html('<%= escape_javascript(render :partial => "follow_form", :locals => {:user => @user}) %>');
// $("#followers").html('<%= @user.followers.count %>');
// $(".stories").html('<%= escape_javascript(render :partial => "story", :locals => {:user.story => @story}) %>');