config/routes.rb
Whichizrite::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"},
                      :controllers => {:registrations => "users/registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
    get "login",    :to => "users/sessions#new"
    get "logout",   :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete",   :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to => "users/registrations#password"
    patch "settings/password" => "users/registrations#settings_password"
    put "settings/password" => "users/registrations#settings_password"
    get "settings/privacy", :to => "users/registrations#privacy"
    patch "settings/privacy" => "users/registrations#settings_privacy"
    put "settings/privacy" => "users/registrations#settings_privacy"
  end 

  get 'feed', to: 'pages#feed'

  resources :users do
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :visibility
      get :unpend
    end
  end

  
  resources :pages

  resources :posts do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments do
    member do
      get :vote_up
      get :vote_down
      get :unvote
    end
  end
  resources :votes

  get 'categories/:category', to: 'posts#index', as: :category

  get 'tags/:tag', to: 'posts#index', as: :tag

  root :to => 'pages#home'

end

app/views/shared/_comment_form.html.erb
<%= simple_form_for(@comment, remote: true, :validate => true ) do |f| %>
 <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.hidden_field :post_id, value: @post.id %>
    <%= f.text_area :comment, placeholder: "write a comment..." %>
  </div>
  <div class="submit">
    <%= f.submit "Comment", class: "btn btn-large btn-primary pull-right", disable_with: "Saving..."   %>
  </div>
<% end %>

app/views/shared/_commentvote.html.erb
<% if user_signed_in? && (comment.user == current_user) %>
	<% if comment.voted_by?(current_user) %>
		<% if current_user.voted_for?(comment) %>
			<!-- If signed in and voted for -->
			<span class="vote-items">
				<span class="like">
					<%= link_to unvote_comment_path(comment), class: "wir", style: "color: #46a546;  font-size: 12px;", remote: true do %>
						<i class="icon-thumbs-up" style="padding:2px;"></i>
					<% end %>
				</span>
				<span class="stats">
					<%= render :partial => "shared/commentvotecount", locals: {comment: comment}  %>
				</span>
				<span class="dislike">
					<%= link_to vote_down_comment_path(comment), class: "wiw", remote: true do %>
						<i class="icon-thumbs-down" style="padding:2px;"></i>
					<% end %>
				</span>
			</span>
			<!-- End If signed in and voted for -->
		<% else %>
			<!-- If signed in & voted against -->
			<span class="vote-items">
				<span class="like">
					<%= link_to vote_up_comment_path(comment), class: "wir", remote: true do %>
						<i class="icon-thumbs-up" style="padding:2px;"></i>
					<% end %>
				</span>
				<span class="stats">
					<%= render :partial => "shared/commentvotecount", locals: {comment: comment}  %>
				</span>
				<span class="dislike">
					<%= link_to unvote_comment_path(comment), class: "wiw", style: "color: #9d261d;", remote: true do %>
						<i class="icon-thumbs-down" style="padding:2px; font-size: 12px;"></i>
					<% end %>
				</span>
			</span>
			<!-- End If signed in & voted against -->
		<% end %>
	<% else %>
		<!-- If signed in but hasn't voted yet -->
		<span class="vote-items">
			<span class="like">
				<%= link_to vote_up_comment_path(comment), remote: true do %>
					<i class="icon-thumbs-up" style="padding:2px;"></i>
				<% end %>
			</span>
			<span class="stats">
				<%= render :partial => "shared/commentvotecount", locals: {comment: comment}  %>
			</span>
			<span class="dislike">
				<%= link_to vote_down_comment_path(comment), remote: true do %>
					<i class="icon-thumbs-down" style="padding:2px;"></i>
				<% end %>
			</span>
		</span>
		<!-- End If signed in but hasn't voted yet -->
	<% end %>
<% else %>
	<!-- If signed in but hasn't voted yet -->
	<span class="vote-items">
		<span class="like">
			<%= link_to vote_up_comment_path(comment), class: "wir" do %>
				<i class="icon-thumbs-up" style="padding:2px;"></i>
			<% end %>
		</span>
		<span class="stats">
			<%= render :partial => "shared/commentvotecount", locals: {comment: comment}  %>
		</span>
		<span class="dislike">
			<%= link_to vote_down_comment_path(comment), class: "wiw" do %>
				<i class="icon-thumbs-down" style="padding:2px;"></i>
			<% end %>
		</span>
	</span>
	<!-- End If signed in but hasn't voted yet -->
<% end %>

app/views/shared/_commentvotecount.html.erb
<% if comment.votes_for == comment.votes_against %>
    <span class="votecount" style= "line-height: 22px; padding: 0px 5px;">score</span>
<% elsif comment.votes_for < comment.votes_against %>
    <span class="votecount" style= "line-height: 22px; color: white; background-color:#ca0000; display:block; font-weight: bold;"><%= comment.votes_against - comment.votes_for %></span>
<% else %>
	<span class="votecount" style= "line-height: 22px; color: white; background-color:#46a546; display:block; font-weight: bold;"><%= comment.votes_for - comment.votes_against %></span>
<% end %>

app/views/shared/_feed.html.erb
<% @feed_items = Post.paginate(page: params[:page]) %>

<% unless @feed_items.empty? %>
	<ol class="posts-list">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>" class="post-item row">
	<% if feed_item.p_image.exists? %>
		<div class="post-pic col-md-3 col-sm-3 col-xs-3 ">		
			<%= link_to image_tag(feed_item.p_image.url(:thumb)), post_path(feed_item) %>		
		</div>
		<div class="post-content col-md-8 col-sm-8 col-xs-8 ">
			<%= render partial: 'shared/feed_content', locals: {feed_item: feed_item} %>
		</div>
	<% else %>
		<div class="post-content col-md-11 col-sm-11 col-xs-11">
			<div class="post-title-bar row">
				<span class="post-title col-md-10 col-sm-10 col-xs-10">
					<h2><%= link_to feed_item.p_title, post_path(feed_item) %><span class="post-cat"><%= link_to Category.find(feed_item.category_id).cat_name %></span>
					</h2>					
				</span>				
			</div>
			<span class="post-info">by: <span class="post-user"><%= link_to feed_item.user.name, feed_item.user %> on <%= feed_item.created_at.strftime("%b #{feed_item.created_at.day.ordinalize} %Y, %I:%M %p") %></span>
				<span class="post-fb">
					<%= link_to post_path(feed_item)  do %>
						<i class="glyphicon glyphicon-comment"></i><% if feed_item.comments.count > 0 %><span style="margin-left:5px;"><%= feed_item.comments.count %></span><% end %>
					<% end %>
				</span>
			</span>
			<p><%= the_excerpt(feed_item) %></p>					
		</div>

	<% end %>
	<div class="post-vote col-xs-1 col-sm-1">
		<div class="myvote-<%= feed_item.id %>">
			<%= render :partial => "shared/feedvote", locals: {feed_item: feed_item} %>
		</div>
	</div>						
</li>

app/views/shared/_links.html.erb
<div class="otherLinks">
	<%= link_to user_omniauth_authorize_path(:facebook,:display=>"popup"), :class => "fb-button", :"data-width" => 600, :"data-height" => 400  do %>
		<i class="icon-facebook-sign"></i>Login with Facebook
	<% end %> <% if !current_page?(register_path) %> or <%= link_to "Sign up now!", register_path, :class => "signup-btn"  %><% end %>
</div>

app/views/shared/_login.html.erb
<div id="loginModal" class="login-form modal hide fade" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4><%= link_to image_tag("wir_title.png", alt: "title"), root_path, id: "title" %></h4>
	</div>
	<div class="row">
		<div class="myLogin">
			<%= render "shared/loginForm" %>		
		</div>
	</div>
</div>

app/views/shared/_loginForm.html.erb
<%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :validate => true, :html => { :class => "login-form form-horizontal"}) do |f| %>

	<div class="login-header">
		<h3>Login</h3>
	</div>
	
	<%= f.text_field :login, placeholder: "username/email" %>
	
	<%= f.password_field :password, placeholder: "password" %>

	<label class="checkbox">
      <input id="user_remember_me" label="remember me?" name="user[remember_me]" type="checkbox" value="1">&nbsp;Remember me
    </label>    

    <div class="forgotLink pull-right">
		<%= link_to "I forgot my password", new_password_path('user') %>
	</div>

	<%= f.submit 'Login', :class => "btn btn-primary" %>


	<%= render "shared/links" %>

<% end %>

app/views/shared/_myfeed.html.erb
<% @feed_items = current_user.feed.paginate(page: params[:page]) %>

<% unless @feed_items.empty? %>
	<ol class="posts-list">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post.html.erb
<div id="postModal" class="post-form modal hide fade" tabindex="-1" role="dialog" aria-labelledby="postModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4><%= link_to image_tag("wir_title.png", alt: "title"), root_path, id: "title" %></h4>
	</div>
	<div class="myPost">
		<%= simple_form_for(@post, :html => { :class => "post-form", :multipart => true } ) do |f| %>
			<%= render 'shared/error_messages', object: f.object %>

		    <%= f.text_field :p_title, placeholder: "Title" %>

		    <%= f.file_field :p_image %>

		    <% if current_user.admin? %>
		    	<%= f.collection_select :cat_id, Category.all, :id, :cat_name  %>
		    <% else %>
		    	<%= f.collection_select :cat_id, Category.where("id IS NOT 7"), :id, :cat_name  %>
		    <% end %>

		    <%= f.text_field :tag_list, placeholder: "Tags (separated by commas)" %>

		    <%= f.text_area :p_body, placeholder: "What do you want to say..." %>

		    <%= f.submit "Post", class: "btn btn-primary" %>
		<% end %>
	</div>
</div>

app/views/shared/_postform.html.erb
<%= simple_form_for(@post, :validate => true, :html => { :class => "post-form inline-form", :multipart => true } ) do |f| %>
    <div class="post-head">
        <h3>Create a new story</h3>
        <p>Feel free to express yourself. You can use the anonymous checkbox to keep your identity a secret.</p>
    </div>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.text_field :p_title, placeholder: "Title" %>
    
    <%= f.file_field :p_image %>

    <% if current_user.admin? %>
    	<%= f.collection_select :cat_id, Category.all, :id, :cat_name  %>
    <% else %>
    	<%= f.collection_select :cat_id, Category.where("id != 1"), :id, :cat_name  %>
    <% end %>

    <%= f.text_field :tag_list, placeholder: "Tags (separated by commas)" %>

    <%= f.text_area :p_body, placeholder: "What do you want to say..." %>

    <label class="checkbox">
        <input id="post_anonymous" label="Post anonymously?" name="post[anonymous_post]" type="checkbox" value"1"> post anonymously?
    </label>
    
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_postmodal.html.erb
<div id="postModal" class="post-form modal hide fade" tabindex="-1" role="dialog" aria-labelledby="postModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
		<h4><%= link_to image_tag("wir_title.png", alt: "title"), root_path, id: "title" %></h4>
	</div>
	<div class="myPost">
		<%= render "shared/postform" %>
	</div>
</div>

app/views/shared/_vote.html.erb
<% if user_signed_in? && (feed_item.user == current_user) %>
	<% if feed_item.voted_by?(current_user) %>
		<% if current_user.voted_for?(feed_item) %>
			<!-- If signed in and voted for -->
			<span class="vote-items">
				<span class="like col-xs-4 col-md-4 col-xs-12 col-md-12">
					<%= link_to unvote_post_path(feed_item), class: "wir", style: "color: #46a546;  font-size: 16px;", remote: true do %>
						<i class="icon-thumbs-up"></i>
					<% end %>
				</span><span class="stats col-xs-4 col-md-4"><%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %>
				</span><span class="dislike col-xs-4 col-md-4">
					<%= link_to vote_down_post_path(feed_item), class: "wiw", remote: true do %>
						<i class="icon-thumbs-down"></i>
					<% end %>
				</span>
			</span>
			<!-- End If signed in and voted for -->
		<% else %>
			<!-- If signed in & voted against -->
			<span class="vote-items">
				<span class="like col-xs-4 col-md-4">
					<%= link_to vote_up_post_path(feed_item), class: "wir", remote: true do %>
						<i class="icon-thumbs-up"></i>
					<% end %>
				</span><span class="stats col-xs-4 col-md-4"><%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %>
				</span><span class="dislike col-xs-4 col-md-4">
					<%= link_to unvote_post_path(feed_item), class: "wiw", style: "color: #9d261d; font-size: 16px;", remote: true do %>
						<i class="icon-thumbs-down"></i>
					<% end %>
				</span>
			</span>
			<!-- End If signed in & voted against -->
		<% end %>
	<% else %>
		<!-- If signed in but hasn't voted yet -->
		<span class="vote-items">
			<span class="like col-xs-4 col-md-4">
				<%= link_to vote_up_post_path(feed_item), class: "wir", remote: true do %>
					<i class="icon-thumbs-up"></i>
				<% end %>
			</span><span class="stats col-xs-4 col-md-4"><%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %>
			</span><span class="dislike col-xs-4 col-md-4">
				<%= link_to vote_down_post_path(feed_item), class: "wiw", remote: true do %>
					<i class="icon-thumbs-down"></i>
				<% end %>
			</span>
		</span>
		<!-- End If signed in but hasn't voted yet -->
	<% end %>
<% else %>
	<!-- If signed in but hasn't voted yet -->
	<span class="vote-items">
		<span class="like col-xs-4 col-md-4">
			<%= link_to vote_up_post_path(feed_item), class: "wir" do %>
				<i class="icon-thumbs-up"></i>
			<% end %>
		</span><span class="stats col-xs-4 col-md-4">
			<%= render :partial => "shared/votecount", locals: {feed_item: feed_item}  %>
		</span><span class="dislike col-xs-4 col-md-4">
			<%= link_to vote_down_post_path(feed_item), class: "wiw" do %>
				<i class="icon-thumbs-down"></i>
			<% end %>
		</span>
	</span>
	<!-- End If signed in but hasn't voted yet -->
<% end %>

app/views/shared/_votecount.html.erb
<% if feed_item.votes_for == feed_item.votes_against %>
<span class="votecount" style="color: #666666; display:block;" >score</span>
<% elsif feed_item.votes_for < feed_item.votes_against %>
<span class="votecount" style= "color: white; background-color:#ca0000;  display:block; font-weight: bold;"><%= feed_item.votes_against - feed_item.votes_for %></span>
<% else %>
<span class="votecount" style= "color: white; background-color:#46a546;  display:block; font-weight: bold;"><%= feed_item.votes_for - feed_item.votes_against %></span>
<% end %>