config/routes.rb
Whichizrite::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"},
                      :controllers => {:registrations => "users/registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
    get "login",    :to => "users/sessions#new"
    get "logout",   :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete",   :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to => "users/registrations#password"
    patch "settings/password" => "users/registrations#settings_password"
    put "settings/password" => "users/registrations#settings_password"
    get "settings/privacy", :to => "users/registrations#privacy"
    patch "settings/privacy" => "users/registrations#settings_privacy"
    put "settings/privacy" => "users/registrations#settings_privacy"
  end 

  get 'feed', to: 'pages#feed'

  resources :users do
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :visibility
      get :unpend
    end
  end

  
  resources :pages

  resources :posts do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments do
    member do
      get :vote_up
      get :vote_down
      get :unvote
    end
  end
  resources :votes

  get 'categories/:category', to: 'posts#index', as: :category

  get 'tags/:tag', to: 'posts#index', as: :tag

  root :to => 'pages#home'

end

app/models/post.rb
class Post < ActiveRecord::Base
  include AutoHtml
  include PgSearch
  extend FriendlyId
  friendly_id :p_title, use: [:slugged]

  multisearchable :against => [:p_title, :p_body]

  # attr_accessible :p_title, :p_image, :anonymous_post, :p_body, :p_type, 
  #                 :p_body_html, :category_id, :tag_list, :p_media, :p_media_html

  has_attached_file :p_image, styles: {main: "250x250>", large: "600x600>", thumb: "125x125#"},
  							  url: "/assets/images/:id/:style/:basename.:extension",
  							  path: ":rails_root/public/assets/images/:id/:style/:basename.:extension"
  belongs_to :user
  belongs_to :category

  has_many :comments, dependent: :destroy

  has_many :taggings
  has_many :tags, through: :taggings

  after_create :categorize

  acts_as_voteable

  default_scope -> {order('created_at DESC')}

  VALID_WEBSITE_REGEX = /\A(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?\z/ix
  validates_presence_of :user_id, message: "You need to enter a title for this story"
  validates :p_title, presence: true, length: {maximum: 30}
  validates :p_body, presence: true
  validates :category_id, presence: true
  validates :tag_list, presence: true
  # validates :p_media, format: {with: VALID_WEBSITE_REGEX}

  def has_attached_image?
    if self.p_image != nil or self.p_image_url != nil
    end
  end

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless Gallery.where(token: random_token).exists?
    end
  end

  def votecount
    if self.votes_for == self.votes_against 
     self.votes_for - self.votes_against
    elsif self.votes_for > self.votes_against 
       self.votes_for - self.votes_against 
    else
       self.votes_against - self.votes_for
    end 
  end

  def self.cat_list(name)
    cat = Category.find_by_cat_name(name)
    where("category_id = #{cat.id}")
  end

  def self.tagged_with(name)
  	Tag.find_by_name!(name).posts  	
  end

  def self.tag_counts
  	Tag.select("tags.*, count(taggings.tag_id) as count").
  		joins(:taggings).group("taggings.tag_id")
  end

  def tag_list
  	tags.map(&:name).join(", ")
  end

  def tag_list=(names)
  	self.tags = names.split(",").map do |n|
  		Tag.where(name: n.strip).first_or_create!
  	end
  end

  def self.featured_posts
    where("cat_id = 1")
  end

  def self.from_users_followed_by(user)
    followed_user_ids="SELECT followable_id FROM follows
                      WHERE follower_id = :user_id"
    where("user_id IN (#{followed_user_ids}) OR origin_user_id = :user_id",
      user_id: user.id)    
  end

  def self.posts_from_me(user)
    where("origin_user_id = :user_id", user_id: user.id)    
  end

  auto_html_for :p_body do
    html_escape
    image
    youtube(:width => 438, :height => 246)
    soundcloud(:maxwidth => '438')
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  auto_html_for :p_media do
    html_escape
    image
    youtube(:width => 438, :height => 246)
    soundcloud(:maxwidth => '438')
    worldstar(:width => 448, :height => 374)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

  AutoHtml.add_filter(:worldstar).with(:width => 448, :height => 374) do |text,options|
    text.gsub(/http:\/\/www\.worldstarhiphop\.com\/videos\/video\.php\?v\=(wshh[A-Za-z0-9]+)/) do
      video_id = $1
      width  = options[:width]
      height = options[:height]
      %{<object width="448" height="374"><param name="movie" value="http://www.worldstarhiphop.com/videos/e/16711680/#{video_id}"><param name="allowFullScreen" value="true"></param><embed src="http://www.worldstarhiphop.com/videos/e/16711680/#{video_id}" type="application/x-shockwave-flash" allowFullscreen="true" width="448" height="374"></embed></object>}
    end
  end

  def categorize
    youtube_regex = /https?:\/\/(www.)?(youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/watch\?feature=player_embedded&v=)([A-Za-z0-9_-]*)(\&\S+)?(\S)*/
    youtube_id = $3
    worldstar_regex = /http:\/\/www\.worldstarhiphop\.com\/videos\/video\.php\?v\=(wshh[A-Za-z0-9]+)/
    worldstar_id = $1
    if self.p_media == "" && self.p_image_url == "" && self.p_image_file_name == nil
      self.p_type = 'text'
      self.save
    else
      if self.p_media != ""
        if youtube_regex.match(self.p_media)
          youtube_regex = /https?:\/\/(www.)?(youtube\.com\/watch\?v=|youtu\.be\/|youtube\.com\/watch\?feature=player_embedded&v=)([A-Za-z0-9_-]*)(\&\S+)?(\S)*/
          youtube_id = $3
          self.p_type = 'video'
          link = 'http://img.youtube.com/vi/' + youtube_id + '/0.jpg'
          self.p_image = URI.parse(link).to_s
          self.save
        elsif worldstar_regex.match(self.p_media)
          link = Nokogiri::HTML(open(self.p_media)).css("meta[property='og:image']").first.attributes["content"]
          self.p_image = URI.parse(link).to_s
          self.p_type = 'video'
          self.save
        else
          self.p_type = 'image'
          text = self.p_media.to_s
          self.p_image = URI.parse(text).to_s
          self.save      
        end 
      elsif self.p_image_url != ""
          self.p_type = 'image'
          text = self.p_image_url.to_s
          self.p_image = URI.parse(text).to_s
          self.save
      else
          self.p_type = 'image'
          self.save 
      end
    end
  end

  def img_from_url(url)
    self.p_image = URI.parse(url).to_s    
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_filter :authenticate_user!, only: [:create, :destroy, :vote_up, :vote_down]
    before_filter :correct_user, only: :destroy
    skip_before_filter :verify_authenticity_token, :only => [:vote_up, :vote_down, :unvote]    
	def show
		@post = Post.friendly.find(params[:id])
        @comment = Comment.new
        @categories = Category.all
        @page_title = @post.p_title
        @page_url = "http://localhost:3000"+ post_path(@post)
        @page_type = @post.p_type
        if @post.p_type == 'image'
            @page_image = @post.p_image
        else
            @page_image = 'http://localhost:3000/assets/whichizrite.jpg'
        end
		respond_to do |format|
            format.html # show.html.erb
        end  
	end

    def index
        if params[:tag]
            @posts = Post.tagged_with(params[:tag])
        elsif params[:query]
            @pg_search_documents = PgSearch.multisearch(params[:query])
            @query = params[:query]
            @posts = Post.all 
        else
            @posts = Post.cat_list(params[:category])
        end       
    end

    def new
        if current_or_guest_user.name == "Guest"
            flash[:notice] = "You need to login before you can create a post."
            redirect_to root_path
        else
            @post = current_user.posts.build(post_params)
            @categories = Category.all
        end
    end
    
    def destroy
        @post = Post.friendly.find(params[:id])
        @post.destroy

        flash[:notice] = "Post successfully deleted."
        redirect_to root_path
    end

	def create
		@post = current_user.posts.build(post_params)
        @categories = Category.all
        if @post.anonymous_post? 
            @post.user_id = User.find_by_username('anonymous').id
            @post.origin_user_id = current_user.id
        else
            @post.origin_user_id = current_user.id
        end

		respond_to do |format|
        	if @post.save 
                current_user.fb_publish(@post.p_title, post_path(@post))
                format.html {redirect_to root_path, :notice => "Post created!"}
                format.json {render json: @post, status: :created, location: @post}
                format.js
        	else
                # @feed_items = []
                format.html {render 'posts/new'}
                format.json {render json: @post.errors, status: :unprocessable_entity}
                format.js {render 'posts/new'}
        	end
        end
	end

    # def edit
    #     if current_or_guest_user.name == "Guest"
    #         flash[:notice] = "You do not have permission to carry out this function."
    #         redirect_to root_path
    #     else
    #         @post = Post.friendly.find(params[:id])
    #         @categories = Category.all
    #     end        
    # end

    # def update
    #     @post = Post.friendly.find(params[:id])
    #     respond_to do |format|
    #         if @post.update_attributes(post_params) 
    #             current_user.fb_publish(@post.p_title, post_path(@post))
    #             format.html {redirect_to root_path, :notice => "Post updated!"}
    #             format.json {render json: @post, status: :created, location: @post}
    #             format.js
    #         else
    #             # @feed_items = []
    #             format.html {render 'posts/new'}
    #             format.json {render json: @post.errors, status: :unprocessable_entity}
    #             format.js {render 'posts/new'}
    #         end
    #     end        
    # end

    def vote_up
        @post = Post.friendly.find(params[:id])
        if current_or_guest_user == "Guest"
            flash[:notice] = "You do not have permission to carry out this function."
            redirect_to root_path
        else
            if @post.user == current_user || @post.user.private_followable == false || current_user.following?(@post.user)
                if current_user.voted_against?(@post)
                    @post.update_attribute("downcount", @post.downcount - 1)
                    @post.update_attribute("upcount", @post.upcount + 1)
                    @post.save
                else
                    @post.update_attribute("upcount", @post.upcount + 1)
                    @post.save
                end
                # PrivatePub.publish_to("/#{@post.user_id}/notifications", "alert('#{current_user.username} voted on your post.');")
                current_user.vote_exclusively_for(@post)              
                respond_to do |format|
                    format.html { redirect_to @post }
                    format.js
                end
                current_user.fb_publish(@post.p_title, post_path(@post))
                UserMailer.post_vote(current_user, @post).deliver  
            else
                flash[:notice] = "You need to follow user in order to carry out this function"
                redirect_to user_path(@post.user)
            end
        end
    end

    def vote_down
        @post = Post.friendly.find(params[:id])
        if current_or_guest_user == "Guest"
            flash[:notice] = "You do not have permission to carry out this function."
            redirect_to root_path
        else
            if @post.user == current_user || @post.user.private_followable == false || current_user.following?(@post.user)
                if current_user.voted_for?(@post)
                    @post.update_attribute("upcount", @post.upcount - 1)
                    @post.update_attribute("downcount", @post.downcount + 1)
                    @post.save
                else
                    @post.update_attribute("downcount", @post.downcount + 1)
                    @post.save
                end 
                # PrivatePub.publish_to("/#{@post.user_id}/notifications", "alert('#{current_user.username} voted on your post.');")
                current_user.vote_exclusively_against(@post)
                # current_user.notify_vote(@post)
                respond_to do |format|
                    format.html { redirect_to @post}
                    format.js
                end
                current_user.fb_publish(@post.p_title, post_path(@post))
                UserMailer.post_vote(current_user, @post).deliver 
            else
                flash[:notice] = "You need to follow user in order to carry out this function"
                redirect_to user_path(@post.user)
            end
        end
    end

    def unvote
        @post = Post.friendly.find(params[:id])
        if current_or_guest_user == "Guest"
            flash[:notice] = "You do not have permission to carry out this function."
            redirect_to root_path
        else
            if @post.user == current_user || @post.user.private_followable == false || current_user.following?(@post.user)
                if current_user.voted_for?(@post)
                    @post.update_attribute("upcount", @post.upcount - 1)
                    @post.save
                else
                    @post.update_attribute("downcount", @post.downcount - 1)
                    @post.save
                end
                current_user.unvote_for(@post)
                respond_to do |format|
                    format.html { redirect_to @post}
                    format.js
                end
            else
                flash[:notice] = "You do not have permission to carry out this function."
                redirect_to root_path
            end
        end        
    end

    private
        def correct_user
            @post = current_user.id == Post.friendly.find(params[:id]).origin_user_id
            redirect_to root_url if @post.nil?            
        end

        def post_params
            params.fetch(:post, {}).permit(:p_title, :p_image, :p_image_url, :anonymous_post, :p_body, 
                                         :p_body_html, :p_media, :p_type, :category_id,
                                         :tag_list, :upcount, :downcount, :origin_user_id)
        end

        def tag_params
            params.require(:tag).permit(:name)
        end

        def category_params
            params.fetch(:category, {}).permit(:cat_name)
        end

end

app/views/posts/_addImage.html.erb
<div id="addImage" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addImageLabel" aria-hidden="true">
    <div class="modal-header">
        <button id="imgClose" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <%= image_tag("wir_symbol.png", alt: "logo") %><h2>Attach an Image</h2>
    </div>	
    <div class="addImageForm">    		    
	    <div class="modal-info">
	    	<a href="#" class="addFromFile">Upload</a><a href="#" class="addFromUrl">Paste an image link</a>	    	
	    	<input id="post_p_image" name="post[p_image]" type="file" data-provide="fileupload" style="display:none;">
	    	<input id="post_p_image_url" name="post[p_image_url]" type="text"  style="display:none;">
	    	<img id="test-pic" src="#" alt="your image" hidden="true" />
	    	<div class="test"></div>    	
			<button id="addImgBtn" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Save</button>
	    </div>
    </div>  
</div>

app/views/posts/_addPic.html.erb
<div id="addPic" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addPicLabel" aria-hidden="true">
    <div class="addPicForm">
    	<div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
	        <h4>Add Attachment</h4>
	    </div>	    
	    <div class="modal-info">
	    	<input id="post_p_image" name="post[p_image]" type="file" data-provide="fileupload">
	    </div>
	    <div class="modal-footer">
			<button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Save</button>
		</div>
    </div>  
</div>

app/views/posts/_addVideo.html.erb
<div id="addVideo" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="addVideoLabel" aria-hidden="true">	
	<div class="modal-header">
        <button id="videoClose" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <%= image_tag("wir_symbol.png", alt: "logo") %><h2>Add a video</h2>
    </div>
    <div class="addVideoForm">	    
	    <div class="modal-info">
	    	<p>Please paste the Youtube or World Star Hip Hop link you wish to share.</p>
	    	<input id="post_p_media" name="post[p_media]" type="text" data-provide="videolink" data-validate="true">
	    	<div class="test"></div>
	    	<button id="addVideoBtn" class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Add To Post</button>
	    </div>
    </div>  
</div>

app/views/posts/_editpostform.html.erb
<div class="page-container">
    <div class="pf-header">
        <h3>Share a Story</h3>
        <p>Feel free to express yourself. You can use the anonymous checkbox to keep your identity a secret.</p>
    </div>
    <%= simple_form_for(@post, :validate => true, :html => { :class => "post-form", :multipart => true } ) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.input :p_title, placeholder: "Title", auto_focus: true, label: false %>

        <div class="attachment">
            <div class="att-btns">
                <button data-toggle="modal" href="#addImage" class="btn"><span class="icon-picture"></span></button><button data-toggle="modal" href="#addVideo" class="btn"><span class="icon-facetime-video"></span></button><!-- <button data-toggle="modal" href="addLink" class="btn"><span class="icon-link"></span -->></button>
            </div>
            <%= render 'addImage'%>
            <%= render 'addVideo'%>       
            <div class="post-checkbox">
                <label class="checkbox">
                    <input id="post_anonymous" label="Post anonymously?" name="post[anonymous_post]" type="checkbox" value"1"> post anonymously?
                </label>
            </div>
        </div>
        <div class="preview">
            <img id="preview-pic" src="#" alt="your image" hidden="true" />
            <div class="media"></div>
            <button type="button" class="close" id="clearfile" data-dismiss="fileupload">&times;</button>        
        </div>

        <% if @post.p_type == 'image' || @post.p_type == 'video' %>
            <% if @post.p_type == 'image' %>
                <div class="temp-preview">
                    <%= image_tag(@post.p_image_file_name) %>
                    <button type="button" class="close" id="cleartemp" data-dismiss="fileupload">&times;</button>     
                </div>
            <% else %>
                <div class="temp-preview">
                    <%= @post.p_media_html %>
                    <button type="button" class="close" id="cleartemp" data-dismiss="fileupload">&times;</button>
                </div>                
            <% end %>
        <% end %>

        <% if current_user.admin? %>
            <%= f.collection_select :category_id, Category.all, :id, :cat_name, label: false  %>
        <% else %>
            <%= f.collection_select :category_id, Category.where("id != 1"), :id, :cat_name, label: false  %>
        <% end %>

        <%= f.input :tag_list, placeholder: "Tags (separated by commas)", label: false %>

        <%= f.input :p_body, placeholder: "What do you want to say...", label: false %>
        <div class="submitPost">
            <%= f.submit "Post", class: "btn btn-primary", disable_with: "Saving..."  %>
        </div>
        
    <% end %>
</div>

app/views/posts/_post.html.erb
<li id="<%= post.id %>" class="post-item row">
	<% if post.p_image.exists? %>
		<div class="post-pic col-md-3 col-sm-3 col-xs-3">	
			<%= link_to image_tag(post.p_image.url(:thumb)), post_path(post) %>		
		</div>
		<div class="post-content col-md-8 col-sm-8 col-xs-8">
			<div class="post-title-bar row">
				<% if signed_in? && current_user.id == post.origin_user_id %>
					<span class="post-title col-xs-11 col-sm-11">
						<h2><%= link_to post.p_title, post_path(post) %><span class="post-cat"><%= link_to Category.find(post.category_id).cat_name %></span></h2>
					</span>
					<span class="post-delete col-xs-1 col-sm-1">					
						<%= link_to post, method: :delete,
											data: {confirm: "You sure?"},
											title: post.p_title do %>
							<i class="icon-trash"></i>						
						<% end %>
					</span>
				<% else %>
					<span class="post-title col-xs-11 col-sm-11">
						<h2><%= link_to post.p_title, post_path(post) %><span class="post-cat"><%= link_to Category.find(post.category_id).cat_name %></span></h2>
					</span>
				<% end %>
			</div>
			<span class="post-info">by: <span class="post-user"><%= link_to post.user.name, post.user %> on <%= post.created_at.strftime("%b #{post.created_at.day.ordinalize} %Y, %I:%M %p") %></span></span>
			<p><%= the_excerpt(post) %></p>
			<span class="post-fb">
				<%= link_to post_path(post)  do %>
					<i class="icon-comment"></i><% if post.comments.count > 0 %><span style="margin-left:5px;"><%= post.comments.count %></span><% end %><span style="margin-left:5px;"><%= "comment".pluralize(post.comments.count) %></span>
				<% end %>
			</span>
		</div>
	<% else %>
		<div class="post-content col-xs-11 col-sm-11">
			<div class="post-title-bar row">
				<% if current_user == post.user %>
					<span class="post-title col-md-11 col-sm-11 col-xs-11">
						<h2><%= link_to post.p_title, post_path(post) %><span class="post-cat"><%= link_to Category.find(post.category_id).cat_name %></span></h2>
					</span>
					<span class="post-delete col-xs-1 col-sm-1">
						<% if current_user.id == post.origin_user_id %>
							<%= link_to post, method: :delete,
												data: {confirm: "You sure?"},
												title: post.p_title do %>
								<i class="icon-trash"></i>
							<% end %>
						<% end %>
					</span>
				<% else %>
					<span class="post-title col-xs-11 col-sm-11">
						<h2><%= link_to post.p_title, post_path(post) %><span class="post-cat"><%= link_to Category.find(post.category_id).cat_name %></span></h2>					
					</span>
				<% end %>
			</div>
			<span class="post-info">by: <span class="post-user"><%= link_to post.user.name, post.user %> on <%= post.created_at.strftime("%b #{post.created_at.day.ordinalize} %Y, %I:%M %p") %></span></span>
			<p><%= the_excerpt(post) %></p>
			<span class="post-fb">
				<%= link_to post_path(post)  do %>
					<i class="icon-comment"></i><% if post.comments.count > 0 %><span style="margin-left:5px;"><%= post.comments.count %></span><% end %><span style="margin-left:5px;"><%= "comment".pluralize(post.comments.count) %></span>
				<% end %>
			</span>
		</div>
	<% end %>
	
	<div class="post-vote col-xs-1 col-sm-1">
		<div class="myvote-<%= post.id %>">
			<%= render :partial => "shared/vote", locals: {post: post, feed_item: post} %>
		</div>
	</div>						
</li>

app/views/posts/_postform.html.erb
<div class="page-container">
    <div class="pf-header">
        <h3>Share a Story</h3>
        <p>Feel free to express yourself. You can use the anonymous checkbox to keep your identity a secret.</p>
    </div>
    <%= simple_form_for(@post, :validate => true, :html => { :class => "post-form", :multipart => true } ) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.input :p_title, placeholder: "Title", auto_focus: true, label: false %>

        <div class="attachment">
            <div class="att-btns">
                <button data-toggle="modal" href="#addImage" class="btn"><span class="icon-picture"></span></button><button data-toggle="modal" href="#addVideo" class="btn"><span class="icon-facetime-video"></span></button><!-- <button data-toggle="modal" href="addLink" class="btn"><span class="icon-link"></span -->></button>
            </div>
            <%= render 'addImage'%>
            <%= render 'addVideo'%>       
            <div class="post-checkbox">
                <label class="checkbox">
                    <input id="post_anonymous" label="Post anonymously?" name="post[anonymous_post]" type="checkbox" value"1"> post anonymously?
                </label>
            </div>
        </div>
        <div class="preview">
            <img id="preview-pic" src="#" alt="your image" hidden="true" />
            <div class="media"></div>
            <button type="button" class="close" id="clearfile" data-dismiss="fileupload">&times;</button>        
        </div>

        <% if @post.p_type == 'image' || @post.p_type == 'video' %>
            Blahhhh
        <% end %>

        <% if current_user.admin? %>
            <%= f.collection_select :category_id, Category.all, :id, :cat_name, label: false  %>
        <% else %>
            <%= f.collection_select :category_id, Category.where("id != 1"), :id, :cat_name, label: false  %>
        <% end %>

        <%= f.input :tag_list, placeholder: "Tags (separated by commas)", label: false %>

        <%= f.input :p_body, placeholder: "What do you want to say...", label: false %>
        <div class="submitPost">
            <%= f.submit "Post", class: "btn btn-primary", disable_with: "Saving..."  %>
        </div>
        
    <% end %>
</div>

app/views/posts/show.html.erb
<div class="main row">
	<!-- Main Post -->
	<div class="col-xs-12 col-sm-8">
		<div class="post-item">
			<div class="post-header row">
				<span class="main-title col-xs-11 col-sm-11">
					<h2><%= @post.p_title %><span class="post-cat"><%= link_to Category.find(@post.category_id).cat_name %></span></h2>
				</span>
				<% if user_signed_in? && current_user == @post.user %>
					<span class="delete-post col-xs-1 col-sm-1">
						<% if current_user.id == @post.origin_user_id %>
							<%= link_to @post, method: :delete,
												data: {confirm: "You user?"},
												title: @post.p_title do %>
								<i class="glyphicon glyphicon-remove"></i>
							<% end %>
						<% end %>
					</span>	
				<% end %>			
			</div><!-- /.main-title -->

			<span class="post-info">by: <span class="post-user"><%= link_to @post.user.name, @post.user %> on <%= @post.created_at.strftime("%b #{@post.created_at.day.ordinalize} %Y, %I:%M %p") %></span></span>
			<div class="post-media row">
				<% if @post.p_type == "text" %>
					<div class="no-img-post-body">	
						<p><%= @post.p_body_html %></p>
						<span class="no-img-post-tags">
							<p>Tags: <%= raw @post.tags.map {|t| link_to t.name, tag_path(t.name) }.join(', ') %></p>
						</span>
					</div>
				<% elsif @post.p_type == "video" %>	
					<span class="post-embed">
						<%= @post.p_media_html %>
					</span>			
				<% else %>					
					<span class="post-embed">
						<%= image_tag @post.p_image.url('large') %>
					</span>
				<% end %>				
				<div class="this-vote">
					<div class="myvote-<%= @post.id %>">
						<%= render :partial => "shared/vote", locals: {feed_item: @post}  %>
					</div>
				</div>
			</div>

			<!-- Post Title Bar -->
			<% if @post.p_type == "video" || @post.p_type == "image" %>
				<div class="post-body">				
					<!-- Post User Feedback Bar -->
					<% if @post.p_image? %>					
						<p><%= @post.p_body %></p>
						<span class="tags">
							<p>Tags: <%= raw @post.tags.map {|t| link_to t.name, tag_path(t.name) }.join(', ') %></p>
						</span>
					<% end %>			
				</div>
			<% end %>

			<div class="google-comment-ad"></div>
		
			<%= render 'shared/comments' %>
			<% if user_signed_in? %>
				<span class="comment-entry row">
					<span class="comment-user col-xs-2 col-sm-2">
						<%= link_to avatar_for(current_user, 'small'), current_user %>
					</span>
					<span class="comment-form col-xs-10 col-sm-10">
						<%= link_to current_user.name, current_user %>
						<%= render 'shared/comment_form' %>
					</span>
				</span>
			<% end %>
		</div>
	</div>

	<!-- Side Bar -->
	<div class="hidden-xs col-sm-4">
		<% if signed_in? %>
			<%= current_user.name %>
			<%= current_user.email %><br>
			<%= link_to "create a new post", new_post_path %>
		<% else %>
			<a href="#loginModal" role="button" class="btn" data-toggle="modal">Login | Sign up</a>
			<%= render "shared/login" %>
		<% end %>
	</div>
</div>