config/routes.rb
Whichizrite::Application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => "login", :sign_out => "logout",
                                                  :sign_up => "register"},
                      :controllers => {:registrations => "users/registrations",
                                       :omniauth_callbacks => "users/omniauth_callbacks"}

  devise_scope :user do
    get "login",    :to => "users/sessions#new"
    get "logout",   :to => "users/sessions#destroy"
    get "register", :to => "users/registrations#new"
    get "delete",   :to => "users/registrations#destroy"
    get "settings", :to => "users/registrations#edit"
    get "settings/password", :to => "users/registrations#password"
    patch "settings/password" => "users/registrations#settings_password"
    put "settings/password" => "users/registrations#settings_password"
    get "settings/privacy", :to => "users/registrations#privacy"
    patch "settings/privacy" => "users/registrations#settings_privacy"
    put "settings/privacy" => "users/registrations#settings_privacy"
  end 

  get 'feed', to: 'pages#feed'

  resources :users do
    member do
      get :follow
      get :unfollow
      get :followers
      get :following
      get :visibility
      get :unpend
    end
  end

  
  resources :pages

  resources :posts do
    member do
      get :vote_up
      get :vote_down
      get :unvote
      get :comment
    end
  end

  resources :comments do
    member do
      get :vote_up
      get :vote_down
      get :unvote
    end
  end
  resources :votes

  get 'categories/:category', to: 'posts#index', as: :category

  get 'tags/:tag', to: 'posts#index', as: :tag

  root :to => 'pages#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "home",   root_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">    
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("wir_logo.png", alt: "logo"), root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>

        <% if signed_in? %>
          <li id="fat-menu" class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- <%= avatar_for(current_user, 'thumb') %> --><%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="profileMenu">
              <li role="presentation">
                <%= link_to "Profile", user_path(current_user), :input_html => {role: "menu-item"} %>
              </li>
              <li role="presentation">
                <%= link_to "Edit Profile", settings_path, :input_html => {role: "menu-item"} %>
              </li>
              <li role="presentation">
                <%= link_to "log out", logout_path, method: "delete", :input_html => {role: "menu-item"} %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "login", login_path, :input_html => {role: "menu-item"} %></li>
        <% end %>
      </ul>
    </div><!-- /.nav-collapse -->      
  </div><!-- /.container --> 
</div><!-- /.navbar --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta content="<%= @page_title %>" property="og:title" />
  <meta content="<%= @page_site_name %>" property="og:site_name" />
  <meta content="<%= @page_url %>" property="og:url" />
  <meta content="<%= @page_type %>" property="og:type" />
  <meta content="<%= @page_image %>" property="og:image" />
  <link rel="image_src" href="<%= @page_image %>" />
  <!-- <link rel="video_src" href="<%= @page_image %>" /> -->
  <%= favicon_link_tag 'favicon.ico' %>

  <%= stylesheet_link_tag    "application", media: "all" %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">  
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <!-- <= render 'shared/channel_nav' unless @disable_chan %> --> 
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>

    <!-- Bootstrap javascripts -->
    <%= javascript_include_tag "application" %>
</body>
</html>